language: node_js
node_js: '6'
sudo: required
addons:
  ssh_known_hosts: paradork.com
notifications:
  email: false
services:
- mongodb
deploy:
  skip_cleanup: true
  provider: script
  script: chmod +x .travis/deploy.sh && .travis/deploy.sh
  on:
    all_branches: true
before_install:
- openssl aes-256-cbc -K $encrypted_ff4d4c896f3c_key -iv $encrypted_ff4d4c896f3c_iv
  -in travis_rsa.enc -out travis_rsa -d
